# pandas

In [1]:
# pip install pandas
# conda install pandas

* numpy를 내부적으로 활용함
* 데이터 분석에 특화된 데이터 구조 제공(테이블, dataframe)
* 다양한 데이터 분석 함수 제공
* 데이터베이스에 쉽게 연결 가능
* json 데이터 html의 table요소를 dataframe으로 손쉽게 변형 가능

# pandas에서 다루는 데이터 타입 2가지
## 1) DataFrame: 2차원의 표형식 데이터 
* python의 dict와도 비슷 하나의 key에 list 형태의 value가 매칭되어 있는 형태
* {key : [value1, value2, value3], key2 : [value1, value2, value3]}
## 2) Series: 1차원의 벡터형식 데이터
* python의 list, tuple, ndarray의 1차원 상태와 비슷

In [2]:
import pandas as pd

# 데이터프레임 만들기
pd.DataFrame({key1: [value1, value2] key2 : [value1, value2]})

In [3]:
df = pd.DataFrame(
        {'이름' : ['홍길동', '둘리', '또치', '도우너'],
         '주소' : ['서울', '의정부', '고양', '성남'],
         '취미' : ['음악감상', '놀기', '달리기', '바이올린']}
        )

In [4]:
df

    이름   주소    취미
0  홍길동   서울  음악감상
1   둘리  의정부    놀기
2   또치   고양   달리기
3  도우너   성남  바이올린

In [5]:
df.shape

(4, 3)

In [6]:
df.ndim

2

In [7]:
df['이름']

0    홍길동
1     둘리
2     또치
3    도우너
Name: 이름, dtype: object

In [8]:
df['이름'].dtype

dtype('O')

In [9]:
print(df['이름'][:2])

0    홍길동
1     둘리
Name: 이름, dtype: object

# Series 만들기
* pd.Series([리스트 자료/튜플], name="컬럼명")
* 이름을 가지고 있는 list / 벡터
* dataframe에서 컬럼 1개를 잘라온 형태

In [10]:
ages = pd.Series([22,53, 35], name="나이")

In [11]:
ages.dtype

dtype('int64')

In [12]:
ages

0    22
1    53
2    35
Name: 나이, dtype: int64

In [13]:
ages[0:2]

0    22
1    53
Name: 나이, dtype: int64

In [14]:
ages[::-1]

2    35
1    53
0    22
Name: 나이, dtype: int64

In [15]:
ages.min()

np.int64(22)

In [16]:
ages.max()

np.int64(53)

In [17]:
ages.sum()

np.int64(110)

In [18]:
ages.cumsum()

0     22
1     75
2    110
Name: 나이, dtype: int64

In [19]:
ages.mean()

np.float64(36.666666666666664)

In [20]:
ages.median()

np.float64(35.0)

# 판다스에서 자료 불러오기, 저장하기
* csv, tsv, excel, json, html, sql
* pd.read_확장자명(파일경로, 옵션)

excel 파일 불러오기

In [50]:
df_excel = pd.read_excel("./data/Online Retail.xlsx")
df_excel

KeyboardInterrupt:

In [22]:
%%time
df_excel2 = pd.read_excel("./data/아파트(매매)_실거래가_20240806113828.xlsx", header=12, usecols=[1,2,3,4,5])
df_excel2

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

CPU times: total: 51.1 s
Wall time: 54.1 s

                       시군구      번지    본번  부번                단지명
0         서울특별시 영등포구 당산동5가      42    42   0          당산삼성래미안4차
1      강원특별자치도 원주시 지정면 가곡리    1512  1512   0  원주롯데캐슬골드파크1차(5단지)
2        대구광역시 달성군 화원읍 구라리    1650  1650   0             대곡역래미안
3             광주광역시 남구 진월동   312-7   312   7                 광명
4             광주광역시 남구 진월동  331-93   331  93                 중흥
...                    ...     ...   ...  ..                ...
37575        서울특별시 송파구 장지동     849   849   0          송파파인타운3단지
37576        부산광역시 사상구 모라동     552   552   0               백양그린
37577        광주광역시 광산구 비아동   152-5   152   5                 호반
37578        부산광역시 사상구 모라동     552   552   0               백양그린
37579         대구광역시 북구 읍내동  1366-2  1366   2               칠곡보성

[37580 rows x 5 columns]

In [23]:
%%time
df_csv = pd.read_csv("./data/아파트(매매)_실거래가_20240806113828.csv", header=12)
df_csv

CPU times: total: 328 ms
Wall time: 407 ms

,NO,시군구,번지,본번,부번,단지명,전용면적(㎡),계약년월,계약일,거래금액(만원),...,층,매수자,매도자,건축년도,도로명,해제사유발생일,거래유형,중개사소재지,등기일자,주택유형
0,1,서울특별시 영등포구 당산동5가,42,42,0,당산삼성래미안4차,115.7800,202407,31,"139,000",...,4,개인,개인,2003,당산로 214,-,직거래,-,-,아파트
1,2,강원특별자치도 원주시 지정면 가곡리,1512,1512,0,원주롯데캐슬골드파크1차(5단지),84.9644,202407,31,"38,900",...,10,개인,개인,2019,신지정로 250,20240802,중개거래,강원 원주시,-,아파트
2,3,대구광역시 달성군 화원읍 구라리,1650,1650,0,대곡역래미안,84.5958,202407,31,"29,500",...,11,개인,개인,2007,비슬로539길 35,-,중개거래,대구 달성군,-,아파트
3,4,광주광역시 남구 진월동,312-7,312,7,광명,70.6250,202407,31,"16,900",...,1,개인,개인,1998,광복마을길 63,-,중개거래,광주 남구,-,아파트
4,5,광주광역시 남구 진월동,331-93,331,93,중흥,84.8400,202407,31,"17,500",...,13,개인,개인,1992,서문대로749번마길 30,-,직거래,-,24.07.31,아파트
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37575,37576,서울특별시 송파구 장지동,849,849,0,송파파인타운3단지,84.9800,202407,1,"117,500",...,14,개인,개인,2008,충민로 152,-,중개거래,서울 송파구,-,아파트
37576,37577,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,000",...,8,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.10,아파트
37577,37578,광주광역시 광산구 비아동,152-5,152,5,호반,59.8800,202407,1,"15,400",...,5,개인,개인,1998,비아로 185,-,중개거래,광주 광산구,24.07.26,아파트
37578,37579,부산광역시 사상구 모라동,552,552,0,백양그린,41.3000,202407,1,"7,500",...,10,개인,개인,1992,모라로110번길 88,-,중개거래,부산 사상구,24.07.19,아파트
37579,37580,대구광역시 북구 읍내동,1366-2,1366,2,칠곡보성,84.9800,202407,1,"21,000",...,9,개인,개인,1992,구암로21길 26,-,중개거래,대구 북구,-,아파트

In [24]:
df_json = pd.read_json("./data/서울특별시_관광지입장정보_2011_2016.json")
df_json

    ForNum  NatNum  addrCd gungu      resNm  rnum   sido  yyyymm
0    44722   75991    1111   종로구        창덕궁     1  서울특별시  201112
1        0   11017    1111   종로구        운현궁     2  서울특별시  201112
2   132399  237330    1111   종로구        경복궁     3  서울특별시  201112
3     3133   21267    1111   종로구        창경궁     4  서울특별시  201112
4    18226   24223    1111   종로구         종묘     5  서울특별시  201112
..     ...     ...     ...   ...        ...   ...    ...     ...
62    5588   44232    1141  서대문구  서대문형무소역사관     8  서울특별시  201512
63       0   22587    1141  서대문구  서대문자연사박물관     9  서울특별시  201512
64   29520    8822    1144   마포구    트릭아이미술관    10  서울특별시  201512
65       3    1647    1165   서초구      헌릉ㆍ인릉    11  서울특별시  201512
66     492   14454    1168   강남구      선릉·정릉    12  서울특별시  201512

[67 rows x 8 columns]

In [27]:
df_html = pd.read_html("./data/corpList.htm")
df_html[0]

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7
0,한국제15호스팩,금융 지원 서비스업,기업인수합병,2024-06-26,12월,유한,NaN,서울특별시
1,에스오에스랩,"측정, 시험, 항해, 제어 및 기타 정밀기기 제조업; 광학기기 제외",산업용 및 차량용 라이다(LiDAR),2024-06-25,12월,정지성,홈페이지 보기,광주광역시
2,미래에셋비전스팩6호,금융 지원 서비스업,기업인수합병,2024-06-24,12월,정명훈,NaN,서울특별시
3,에이치엠씨제7호스팩,금융 지원 서비스업,기타금융,2024-06-24,12월,강신명,NaN,서울특별시
4,파라다이스,유원지 및 기타 오락관련 서비스업,"카지노, 호텔, 복합리조트",2024-06-24,12월,최종환..,홈페이지 보기,서울특별시
5,한중엔시에스,"전동기, 발전기 및 전기 변환 · 공급 · 제어 장치 제조업","수냉식 냉각시스템 ESS Parts, 공랭식 ESS Module Parts, EV ...",2024-06-24,12월,김환식,홈페이지 보기,경상북도
6,KB제29호스팩,금융 지원 서비스업,기업인수합병,2024-06-21,12월,서영화,NaN,서울특별시
7,미래에셋비전스팩5호,금융 지원 서비스업,기업인수합병,2024-06-19,12월,김대호,NaN,서울특별시
8,씨어스테크놀로지,의료용 기기 제조업,심전도검사솔루션 입원환자모니터링솔루션,2024-06-19,12월,이영신,홈페이지 보기,경기도
9,한국제14호스팩,금융 지원 서비스업,기업인수합병,2024-06-19,12월,변성환,NaN,서울특별시
10,디비금융스팩12호,기타 금융업,기업인수 및 합병,2024-06-18,12월,김창희,NaN,서울특별시
11,라메디텍,의료용 기기 제조업,초소형 레이저 의료기기 및 미용기기,2024-06-17,12월,최종석,NaN,서울특별시
12,그리드위즈,"그외 기타 전문, 과학 및 기술 서비스업","수요관리 서비스, 전기차 충전기 모뎀 등",2024-06-14,12월,김구환,홈페이지 보기,경기도
13,다원넥스뷰,사진장비 및 광학기기 제조업,LSMB(Laser Micro Bonding System),2024-06-11,12월,남기중,홈페이지 보기,경기도
14,미래에셋비전스팩4호,금융 지원 서비스업,기업인수목적회사(기타금융서비스),2024-05-29,12월,김정수,NaN,서울특별시

DB에서 자료 읽어오기

In [29]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()

In [30]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/exchange_rate")
conn = engine.connect()
df_sql = pd.read_sql("exchange_rate", con=conn)
conn.close()
df_sql

,date,통화,현찰_사실_때_환율,현찰_사실_때_Spread,현찰_파실_때_환율,현찰_파실_때_Spread,송금_보낼_때_보낼_때,송금_받을_때_받을_때,외화_수표_파실때,매매_기준율,환가_료율,미화_환산율
0,1995-01-03,미국 USD,800.53,1.5,776.87,1.5,791.80,785.60,0.00,788.70,0.00,1.0000
1,1995-01-03,일본 JPY (100),798.89,1.5,775.29,1.5,791.81,782.37,0.00,787.09,0.00,0.9980
2,1995-01-03,유로 EUR,0.00,0.0,0.00,0.0,975.40,959.92,957.94,967.66,7.37,1.2269
3,1995-01-03,중국 CNY,0.00,0.0,0.00,0.0,94.12,0.00,0.00,93.38,1.00,0.1184
4,1995-01-03,홍콩 HKD,103.45,3.0,100.41,3.0,102.74,101.12,0.00,101.93,0.00,0.1292
...,...,...,...,...,...,...,...,...,...,...,...,...
127645,2025-04-15,리비아 LYD,0.00,0.0,0.00,0.0,260.07,254.93,0.00,257.50,0.00,0.1799
127646,2025-04-15,루마니아 RON,0.00,0.0,0.00,0.0,329.99,322.81,0.00,326.40,7.74,0.2280
127647,2025-04-15,미얀마 MMK,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.68,0.00,0.0005
127648,2025-04-15,에티오피아 ETB,0.00,0.0,0.00,0.0,0.00,0.00,0.00,10.81,0.00,0.0076
127649,2025-04-15,우즈베키스탄 UZS,0.00,0.0,0.00,0.0,0.00,0.00,0.00,0.11,0.00,0.0001

In [32]:
engine = create_engine("mysql+pymysql://kict20:kict20@221.155.18.165:3306/titanic")
conn = engine.connect()
passenger = pd.read_sql("p_info", con=conn)
conn.close()
passenger

,PassengerId,Name,Sex,Age,SibSp,Parch
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
4,5,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0
890,891,"Dooley, Mr. Patrick",male,32.0,0,0

# 타이타닉 데이터셋으로 pandas 기능 익히기

In [207]:
df = pd.read_csv("./data/Titanic_train.csv")
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [36]:
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

* 데이터의 일부만 보기
* 앞쪽 head(행개수), 뒷쪽 tail(행개수)
* 기본 값은 5행

In [37]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [39]:
df.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [40]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [47]:
df.tail(60)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
831,832,1,2,"Richards, Master. George Sibley",male,0.83,1,1,29106,18.7500,NaN,S
832,833,0,3,"Saad, Mr. Amin",male,NaN,0,0,2671,7.2292,NaN,C
833,834,0,3,"Augustsson, Mr. Albert",male,23.00,0,0,347468,7.8542,NaN,S
834,835,0,3,"Allum, Mr. Owen George",male,18.00,0,0,2223,8.3000,NaN,S
835,836,1,1,"Compton, Miss. Sara Rebecca",female,39.00,1,1,PC 17756,83.1583,E49,C
836,837,0,3,"Pasic, Mr. Jakob",male,21.00,0,0,315097,8.6625,NaN,S
837,838,0,3,"Sirota, Mr. Maurice",male,NaN,0,0,392092,8.0500,NaN,S
838,839,1,3,"Chip, Mr. Chang",male,32.00,0,0,1601,56.4958,NaN,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
840,841,0,3,"Alhomaki, Mr. Ilmari Rudolf",male,20.00,0,0,SOTON/O2 3101287,7.9250,NaN,S
841,842,0,2,"Mudd, Mr. Thomas Charles",male,16.00,0,0,S.O./P.P. 3,10.5000,NaN,S
842,843,1,1,"Serepeca, Miss. Augusta",female,30.00,0,0,113798,31.0000,NaN,C
843,844,0,3,"Lemberopolous, Mr. Peter L",male,34.50,0,0,2683,6.4375,NaN,C
844,845,0,3,"Culumovic, Mr. Jeso",male,17.00,0,0,315090,8.6625,NaN,S
845,846,0,3,"Abbing, Mr. Anthony",male,42.00,0,0,C.A. 5547,7.5500,NaN,S
846,847,0,3,"Sage, Mr. Douglas Bullen",male,NaN,8,2,CA. 2343,69.5500,NaN,S
847,848,0,3,"Markoff, Mr. Marin",male,35.00,0,0,349213,7.8958,NaN,C
848,849,0,2,"Harper, Rev. John",male,28.00,0,1,248727,33.0000,NaN,S
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C
850,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.00,4,2,347082,31.2750,NaN,S
851,852,0,3,"Svensson, Mr. Johan",male,74.00,0,0,347060,7.7750,NaN,S
852,853,0,3,"Boulos, Miss. Nourelain",female,9.00,1,1,2678,15.2458,NaN,C
853,854,1,1,"Lines, Miss. Mary Conover",female,16.00,0,1,PC 17592,39.4000,D28,S
854,855,0,2,"Carter, Mrs. Ernest Courtenay (Lilian Hughes)",female,44.00,1,0,244252,26.0000,NaN,S
855,856,1,3,"Aks, Mrs. Sam (Leah Rosen)",female,18.00,0,1,392091,9.3500,NaN,S
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.00,1,1,36928,164.8667,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.00,0,0,113055,26.5500,E17,S
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.00,0,3,2666,19.2583,NaN,C
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
860,861,0,3,"Hansen, Mr. Claus Peter",male,41.00,2,0,350026,14.1083,NaN,S
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.00,1,0,28134,11.5000,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.00,0,0,17466,25.9292,D17,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.00,0,0,233866,13.0000,NaN,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.00,0,0,236852,13.0000,NaN,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.00,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.00,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.00,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.00,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.00,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.00,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.00,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.00,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.00,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.00,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.00,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.00,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.00,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.00,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.00,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.00,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.00,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.00,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.00,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.00,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.00,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.00,0,0,370376,7.7500,NaN,Q

In [48]:
# 데이터 프레임 각 컬럼의 데이터타입
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# .info() 
* 컬럼명, null이 아닌 데이터 개수, 데이터타입을 동시에 출력

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

# .describe()
* 데이터 프레임의 숫자 데이터의 기초통계를 보여주는 함수
* count, mean, std, min, 25%, 50%, 75%, max

In [51]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

# 판다스 데이터 프레임에서 일부 자료만 추출하기

* 데이터프레임에서 1개 컬럼만 가져오기

In [ ]:
df.head(1)

In [55]:
df['Name'].ndim

1

In [60]:
df['Name'].shape

(891,)

In [54]:
df[['Name']].ndim

2

In [58]:
df[['Name']].shape

(891, 1)

In [61]:
df[['Name']]

                                                  Name
0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
..                                                 ...
886                              Montvila, Rev. Juozas
887                       Graham, Miss. Margaret Edith
888           Johnston, Miss. Catherine Helen "Carrie"
889                              Behr, Mr. Karl Howell
890                                Dooley, Mr. Patrick

[891 rows x 1 columns]

In [62]:
print(type(df[['Name']]))

<class 'pandas.core.frame.DataFrame'>

In [63]:
print(type(df['Name']))

<class 'pandas.core.series.Series'>

* 2개 이상의 컬럼을 가져오기

In [64]:
df[['Age', 'Name']]

      Age                                               Name
0    22.0                            Braund, Mr. Owen Harris
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    26.0                             Heikkinen, Miss. Laina
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4    35.0                           Allen, Mr. William Henry
..    ...                                                ...
886  27.0                              Montvila, Rev. Juozas
887  19.0                       Graham, Miss. Margaret Edith
888   NaN           Johnston, Miss. Catherine Helen "Carrie"
889  26.0                              Behr, Mr. Karl Howell
890  32.0                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [65]:
df[['Age', 'Name', 'Pclass']]

      Age                                               Name  Pclass
0    22.0                            Braund, Mr. Owen Harris       3
1    38.0  Cumings, Mrs. John Bradley (Florence Briggs Th...       1
2    26.0                             Heikkinen, Miss. Laina       3
3    35.0       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1
4    35.0                           Allen, Mr. William Henry       3
..    ...                                                ...     ...
886  27.0                              Montvila, Rev. Juozas       2
887  19.0                       Graham, Miss. Margaret Edith       1
888   NaN           Johnston, Miss. Catherine Helen "Carrie"       3
889  26.0                              Behr, Mr. Karl Howell       1
890  32.0                                Dooley, Mr. Patrick       3

[891 rows x 3 columns]

* 테이터프레임의 컬럼 순서 바꾸기

In [66]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [67]:
df2 = df[['Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Embarked', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'PassengerId']]
df2

,Survived,Pclass,Name,Sex,Age,Embarked,SibSp,Parch,Ticket,Fare,Cabin,PassengerId
0,0,3,"Braund, Mr. Owen Harris",male,22.0,S,1,0,A/5 21171,7.2500,NaN,1
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,C,1,0,PC 17599,71.2833,C85,2
2,1,3,"Heikkinen, Miss. Laina",female,26.0,S,0,0,STON/O2. 3101282,7.9250,NaN,3
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,S,1,0,113803,53.1000,C123,4
4,0,3,"Allen, Mr. William Henry",male,35.0,S,0,0,373450,8.0500,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,S,0,0,211536,13.0000,NaN,887
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,S,0,0,112053,30.0000,B42,888
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,S,1,2,W./C. 6607,23.4500,NaN,889
889,1,1,"Behr, Mr. Karl Howell",male,26.0,C,0,0,111369,30.0000,C148,890
890,0,3,"Dooley, Mr. Patrick",male,32.0,Q,0,0,370376,7.7500,NaN,891

# 데이터프레임에서 일부 컬럼만 가져오기2
* loc: 인덱스 이름과 컬럼명으로 데이터의 일부를 추출해 가져옴
  * df.loc[시작_row_인덱스 : 끝_row_인덱스, ['컬럼명1', '컬럼명2']
* iloc: 인덱스을 이용해 슬라이싱으로 데이터의 일부를 가져옴
  * df.iloc[시작_row_index : 끝_row_index, 시작_column_index : 끝_column_index]

In [69]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#### loc[시작_row_인덱스 : 끝_row_인덱스, ['컬럼명1', '컬럼명2']

In [71]:
df[['Name', 'Age']]

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [70]:
df.loc[100:130, ['Name', 'Age']]

                                  Name   Age
100            Petranec, Miss. Matilda  28.0
101   Petroff, Mr. Pastcho ("Pentcho")   NaN
102          White, Mr. Richard Frasar  21.0
103         Johansson, Mr. Gustaf Joel  33.0
104     Gustafsson, Mr. Anders Vilhelm  37.0
105              Mionoff, Mr. Stoytcho  28.0
106   Salkjelsvik, Miss. Anna Kristine  21.0
107             Moss, Mr. Albert Johan   NaN
108                    Rekic, Mr. Tido  38.0
109                Moran, Miss. Bertha   NaN
110     Porter, Mr. Walter Chamberlain  47.0
111               Zabour, Miss. Hileni  14.5
112             Barton, Mr. David John  22.0
113            Jussila, Miss. Katriina  20.0
114              Attalah, Miss. Malake  17.0
115              Pekoniemi, Mr. Edvard  21.0
116               Connors, Mr. Patrick  70.5
117    Turpin, Mr. William John Robert  29.0
118           Baxter, Mr. Quigg Edmond  24.0
119  Andersson, Miss. Ellis Anna Maria   2.0
120        Hickman, Mr. Stanley George  21.0
121         Moore, Mr. Leonard Charles   NaN
122               Nasser, Mr. Nicholas  32.5
123                Webber, Miss. Susan  32.5
124        White, Mr. Percival Wayland  54.0
125       Nicola-Yarred, Master. Elias  12.0
126                McMahon, Mr. Martin   NaN
127          Madsen, Mr. Fridtjof Arne  24.0
128                  Peter, Miss. Anna   NaN
129                 Ekstrom, Mr. Johan  45.0
130               Drazenoic, Mr. Jozef  33.0

In [ ]:
df.loc[109, ['Age']]

In [ ]:
df.loc[101, ['Age']] = 29

In [ ]:
print(df.loc[101:102, ['Name', 'Age']])
display(df.loc[101:102, ['Name', 'Age']])
# print(type(df.loc[101, ['Name', 'Age']]))

In [74]:
static = df.describe()
print(type(static))

<class 'pandas.core.frame.DataFrame'>

In [83]:
static.loc['min': 'max', ['Age', 'Fare']]

        Age      Fare
min   0.420    0.0000
25%  20.125    7.9104
50%  28.000   14.4542
75%  38.000   31.0000
max  80.000  512.3292

In [78]:
static

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [81]:
# 75% + ((75%-25%) * 1.5)
static.loc['75%'] + ((static.loc['75%'] - static.loc['25%'] * 1.5))

PassengerId    1001.7500
Survived          2.0000
Pclass            3.0000
Age              45.8125
SibSp             2.0000
Parch             0.0000
Fare             50.1344
dtype: float64

#### df.iloc[시작_row_index : 끝_row_index, 시작_column_index : 끝_column_index]

In [77]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [86]:
df.iloc[4:11, -5:]

    Parch   Ticket     Fare Cabin Embarked
4       0   373450   8.0500   NaN        S
5       0   330877   8.4583   NaN        Q
6       0    17463  51.8625   E46        S
7       1   349909  21.0750   NaN        S
8       2   347742  11.1333   NaN        S
9       0   237736  30.0708   NaN        C
10      1  PP 9549  16.7000    G6        S

In [87]:
df.iloc[4, 4] = 'female'

In [88]:
df.iloc[4, 4]

'female'

In [89]:
df.iloc[:10:-1, ::-1]

,Embarked,Cabin,Fare,Ticket,Parch,SibSp,Age,Sex,Name,Pclass,Survived,PassengerId
890,Q,NaN,7.7500,370376,0,0,32.0,male,"Dooley, Mr. Patrick",3,0,891
889,C,C148,30.0000,111369,0,0,26.0,male,"Behr, Mr. Karl Howell",1,1,890
888,S,NaN,23.4500,W./C. 6607,2,1,NaN,female,"Johnston, Miss. Catherine Helen ""Carrie""",3,0,889
887,S,B42,30.0000,112053,0,0,19.0,female,"Graham, Miss. Margaret Edith",1,1,888
886,S,NaN,13.0000,211536,0,0,27.0,male,"Montvila, Rev. Juozas",2,0,887
...,...,...,...,...,...,...,...,...,...,...,...,...
15,S,NaN,16.0000,248706,0,0,55.0,female,"Hewlett, Mrs. (Mary D Kingcome)",2,1,16
14,S,NaN,7.8542,350406,0,0,14.0,female,"Vestrom, Miss. Hulda Amanda Adolfina",3,0,15
13,S,NaN,31.2750,347082,5,1,39.0,male,"Andersson, Mr. Anders Johan",3,0,14
12,S,NaN,8.0500,A/5. 2151,0,0,20.0,male,"Saundercock, Mr. William Henry",3,0,13
11,S,C103,26.5500,113783,0,0,58.0,female,"Bonnell, Miss. Elizabeth",1,1,12

In [82]:
static

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [91]:
static.iloc[4:7, [1,2,5]]

     Survived  Pclass  Parch
25%       0.0     2.0    0.0
50%       0.0     3.0    0.0
75%       1.0     3.0    0.0

* 특정 컬럼에서 유일값(중복되지 않은 고유한 값) 출력하기 
* .unique()

In [92]:
print(df['Embarked'].unique())

['S' 'C' 'Q' nan]

* .nunique()
* 유일값의 개수를 출력
* nan 값은 무시

In [93]:
df['Embarked'].nunique()

3

* 카테고리 컬럼에서 유일값 별 개수를 세는 함수
* value_counts()

In [94]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [95]:
# ascending 옵션 value의 개수에 따라서 오름차순, 내림차순 정렬
df['Pclass'].value_counts(ascending=True)

Pclass
2    184
1    216
3    491
Name: count, dtype: int64

In [96]:
df['Age'].value_counts(sort=False)

Age
22.00    27
38.00    11
26.00    18
35.00    18
54.00     8
         ..
0.67      1
30.50     2
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

* 데이터를 정렬하는 함수
* sort_values(by="컬럼명")
* order by

In [97]:
df.sort_values(by="Age", ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S

* 기준컬럼 2개로 정렬할 때

In [98]:
df.sort_values(by=['Pclass', "Age"], ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C
793,794,0,1,"Hoyt, Mr. William Fisher",male,NaN,0,0,PC 17600,30.6958,NaN,C
815,816,0,1,"Fry, Mr. Richard",male,NaN,0,0,112058,0.0000,B102,S
839,840,1,1,"Marechal, Mr. Pierre",male,NaN,0,0,11774,29.7000,C47,C
849,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C

* 컬럼을 인덱스로 지정하기
* set_index("컬럼명")

In [102]:
# df.reset_index(inplace=True)

In [103]:
df = df.set_index(["PassengerId", "Name"])
df

,,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Name,,,,,,,,,,
1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [104]:
df.index

MultiIndex([(  1,                             'Braund, Mr. Owen Harris'),
            (  2, 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)'),
            (  3,                              'Heikkinen, Miss. Laina'),
            (  4,        'Futrelle, Mrs. Jacques Heath (Lily May Peel)'),
            (  5,                            'Allen, Mr. William Henry'),
            (  6,                                    'Moran, Mr. James'),
            (  7,                             'McCarthy, Mr. Timothy J'),
            (  8,                      'Palsson, Master. Gosta Leonard'),
            (  9,   'Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)'),
            ( 10,                 'Nasser, Mrs. Nicholas (Adele Achem)'),
            ...
            (882,                                  'Markun, Mr. Johann'),
            (883,                        'Dahlberg, Miss. Gerda Ulrika'),
            (884,                       'Banfield, Mr. Frederick James'),
            (885,                              'Sutehall, Mr. Henry Jr'),
            (886,                'Rice, Mrs. William (Margaret Norton)'),
            (887,                               'Montvila, Rev. Juozas'),
            (888,                        'Graham, Miss. Margaret Edith'),
            (889,            'Johnston, Miss. Catherine Helen "Carrie"'),
            (890,                               'Behr, Mr. Karl Howell'),
            (891,                                 'Dooley, Mr. Patrick')],
           names=['PassengerId', 'Name'], length=891)

In [105]:
df.loc[(889, 'Johnston, Miss. Catherine Helen "Carrie"'): (891, 'Dooley, Mr. Patrick') , ['Pclass', 'Age'] ]

                                                      Pclass   Age
PassengerId Name
889         Johnston, Miss. Catherine Helen "Carrie"       3   NaN
890         Behr, Mr. Karl Howell                          1  26.0
891         Dooley, Mr. Patrick                            3  32.0

In [106]:
df.iloc[888:, [1,3]]

                                                      Pclass   Age
PassengerId Name
889         Johnston, Miss. Catherine Helen "Carrie"       3   NaN
890         Behr, Mr. Karl Howell                          1  26.0
891         Dooley, Mr. Patrick                            3  32.0

* 인덱스를 숫자로 초기화 
* reset_index(drop=True)

In [107]:
df

,,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,Name,,,,,,,,,,
1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [108]:
# df.reset_index(drop=True)
df = df.reset_index()
df

,PassengerId,Name,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

* 컬럼이름 출력하기, 바꾸기
* df.columns

In [158]:
df.columns

Index(['PassengerId', 'Name', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

* 컬럼 이름 변경하기
* rename(columns={'원래이름':'새이름', '원래이름2':'새이름2'}):

In [109]:
df.rename(columns={'PassengerId': 'Pid', 'Survived':'surv'}, inplace=True)
df

,Pid,Name,surv,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [110]:
df.rename(index={0: '영번', 1:'일번'}, inplace=True)
df

,Pid,Name,surv,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
영번,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

In [165]:
df

,Pid,Name,surv,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,"Allen, Mr. William Henry",0,3,male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

* df.columns 로 출력되는 리스트 길이와 같은 새로운 이름의 리스트로 덮어쓰기

In [111]:
df.columns

Index(['Pid', 'Name', 'surv', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [112]:
newName = ['승객번호', '이름', '생존여부', '선실등급', '성별', '나이',
           '형제자매수', '부모자식수', '티켓번호', '티켓가격', 
           '선실번호', '목적지']

In [113]:
df.columns = newName
df

,승객번호,이름,생존여부,선실등급,성별,나이,형제자매수,부모자식수,티켓번호,티켓가격,선실번호,목적지
영번,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q

* 컬럼 추가하기
* 변수명['컬럼명'] = value

In [114]:
df['가족수'] = 0

In [115]:
df

,승객번호,이름,생존여부,선실등급,성별,나이,형제자매수,부모자식수,티켓번호,티켓가격,선실번호,목적지,가족수
영번,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,0
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,0
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S,0
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,0
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C,0
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q,0

In [116]:
df['가족수'] = df['형제자매수'] + df['부모자식수']
df

,승객번호,이름,생존여부,선실등급,성별,나이,형제자매수,부모자식수,티켓번호,티켓가격,선실번호,목적지,가족수
영번,1,"Braund, Mr. Owen Harris",0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S,1
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,1,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,0,112053,30.0000,B42,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,0,111369,30.0000,C148,C,0
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,0,370376,7.7500,NaN,Q,0

* 컬럼 삭제하기
* del df['컬럼명']
* df.drop('컬럼명', axis=1, inplace=True)

In [117]:
del df['형제자매수']
df

,승객번호,이름,생존여부,선실등급,성별,나이,부모자식수,티켓번호,티켓가격,선실번호,목적지,가족수
영번,1,"Braund, Mr. Owen Harris",0,3,male,22.0,0,A/5 21171,7.2500,NaN,S,1
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",0,3,female,35.0,0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,0,112053,30.0000,B42,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,2,W./C. 6607,23.4500,NaN,S,3
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,0,111369,30.0000,C148,C,0
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,0,370376,7.7500,NaN,Q,0

In [118]:
df.pop('부모자식수')
df

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
영번,1,"Braund, Mr. Owen Harris",0,3,male,22.0,A/5 21171,7.2500,NaN,S,1
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S,0
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,113803,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",0,3,female,35.0,373450,8.0500,NaN,S,0
...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S,0
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,112053,30.0000,B42,S,0
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,W./C. 6607,23.4500,NaN,S,3
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,111369,30.0000,C148,C,0
890,891,"Dooley, Mr. Patrick",0,3,male,32.0,370376,7.7500,NaN,Q,0

In [123]:
df = df.drop('가족수', axis=1)
df

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S
4,5,"Allen, Mr. William Henry",0,3,female,35.0,373450,8.0500,NaN,S
5,6,"Moran, Mr. James",0,3,male,NaN,330877,8.4583,NaN,Q
6,7,"McCarthy, Mr. Timothy J",0,1,male,54.0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...
885,886,"Rice, Mrs. William (Margaret Norton)",0,3,female,39.0,382652,29.1250,NaN,Q
886,887,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S
887,888,"Graham, Miss. Margaret Edith",1,1,female,19.0,112053,30.0000,B42,S
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,W./C. 6607,23.4500,NaN,S
889,890,"Behr, Mr. Karl Howell",1,1,male,26.0,111369,30.0000,C148,C

In [184]:
df.columns

Index(['승객번호', '이름', '생존여부', '선실등급', '성별', '나이', '티켓번호', '티켓가격', '선실번호', '목적지',
       '가족수'],
      dtype='object')

In [124]:
drop_cols = ['승객번호', '이름', '티켓번호', '티켓가격', '선실번호', '목적지',
       ]

In [125]:
df.drop(drop_cols, axis=1)

     생존여부  선실등급      성별    나이
일번      1     1  female  38.0
2       1     3  female  26.0
4       0     3  female  35.0
5       0     3    male   NaN
6       0     1    male  54.0
..    ...   ...     ...   ...
885     0     3  female  39.0
886     0     2    male  27.0
887     1     1  female  19.0
888     0     3  female   NaN
889     1     1    male  26.0

[888 rows x 4 columns]

* 데이터 타입 바꾸기
* astype(자료형)
* apply(형변환함수)

In [126]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 888 entries, 일번 to 889
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    888 non-null    int64
 1   이름      888 non-null    object
 2   생존여부    888 non-null    int64
 3   선실등급    888 non-null    int64
 4   성별      888 non-null    object
 5   나이      711 non-null    float64
 6   티켓번호    888 non-null    object
 7   티켓가격    888 non-null    float64
 8   선실번호    203 non-null    object
 9   목적지     886 non-null    object
dtypes: float64(2), int64(3), object(5)
memory usage: 108.6+ KB

In [143]:
df['나이'] = df['나이'].astype('float16')
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 888 entries, 일번 to 889
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    888 non-null    int8
 1   이름      888 non-null    object
 2   생존여부    888 non-null    int64
 3   선실등급    888 non-null    int64
 4   성별      888 non-null    object
 5   나이      711 non-null    float16
 6   티켓번호    888 non-null    object
 7   티켓가격    888 non-null    float64
 8   선실번호    203 non-null    object
 9   목적지     886 non-null    object
dtypes: float16(1), float64(1), int64(2), int8(1), object(5)
memory usage: 97.3+ KB

In [148]:
df['티켓가격'] = df['티켓가격'].apply(float)

In [149]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 888 entries, 일번 to 889
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    888 non-null    object
 1   이름      888 non-null    object
 2   생존여부    888 non-null    int64
 3   선실등급    888 non-null    int64
 4   성별      888 non-null    object
 5   나이      711 non-null    float16
 6   티켓번호    888 non-null    object
 7   티켓가격    888 non-null    float64
 8   선실번호    203 non-null    object
 9   목적지     886 non-null    object
dtypes: float16(1), float64(1), int64(2), object(6)
memory usage: 103.4+ KB

In [200]:
df['승객번호'] = df['승객번호'].apply(lambda x: "짝수" if float(x) % 2 == 0 else "홀수")
df.info()

ValueError: could not convert string to float: '홀수'

In [150]:
df

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S
4,5,"Allen, Mr. William Henry",0,3,female,35.0,373450,8.0500,NaN,S
5,6,"Moran, Mr. James",0,3,male,NaN,330877,8.4583,NaN,Q
6,7,"McCarthy, Mr. Timothy J",0,1,male,54.0,17463,51.8625,E46,S
...,...,...,...,...,...,...,...,...,...,...
885,118,"Rice, Mrs. William (Margaret Norton)",0,3,female,39.0,382652,29.1250,NaN,Q
886,119,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S
887,120,"Graham, Miss. Margaret Edith",1,1,female,19.0,112053,30.0000,B42,S
888,121,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,W./C. 6607,23.4500,NaN,S
889,122,"Behr, Mr. Karl Howell",1,1,male,26.0,111369,30.0000,C148,C

In [159]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 888 entries, 일번 to 889
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승객번호    888 non-null    object
 1   이름      888 non-null    object
 2   생존여부    888 non-null    int64
 3   선실등급    888 non-null    int64
 4   성별      888 non-null    object
 5   나이      711 non-null    float16
 6   티켓번호    888 non-null    object
 7   티켓가격    888 non-null    float64
 8   선실번호    203 non-null    object
 9   목적지     886 non-null    object
dtypes: float16(1), float64(1), int64(2), object(6)
memory usage: 103.4+ KB

# 판다스 데이터프레임에서 조건에 맞는 행만 가져오기
* df[df['컬럼명'] 조건식] 
* 조건식 연산자 <, <=, >, >=, ==, !=, &, |

In [163]:
df[df['승객번호'] == "3"]

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
2,3,"Heikkinen, Miss. Laina",1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S
258,3,"Ward, Miss. Anna",1,1,female,35.0,PC 17755,512.3292,NaN,C
514,3,"Coleff, Mr. Satio",0,3,male,24.0,349209,7.4958,NaN,S
770,3,"Lievens, Mr. Rene Aime",0,3,male,24.0,345781,9.5000,NaN,S

In [204]:
df[df['승객번호'] == "홀수"]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
0,홀수,"Braund, Mr. Owen Harris",0,3,male,22.0,A/5 21171,7.2500,NaN,S,1
2,홀수,"Heikkinen, Miss. Laina",1,3,female,26.0,STON/O2. 3101282,7.9250,NaN,S,0
4,홀수,"Allen, Mr. William Henry",0,3,male,35.0,373450,8.0500,NaN,S,0
6,홀수,"McCarthy, Mr. Timothy J",0,1,male,54.0,17463,51.8625,E46,S,0
8,홀수,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1,3,female,27.0,347742,11.1333,NaN,S,2
...,...,...,...,...,...,...,...,...,...,...,...
882,홀수,"Dahlberg, Miss. Gerda Ulrika",0,3,female,22.0,7552,10.5167,NaN,S,0
884,홀수,"Sutehall, Mr. Henry Jr",0,3,male,25.0,SOTON/OQ 392076,7.0500,NaN,S,0
886,홀수,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S,0
888,홀수,"Johnston, Miss. Catherine Helen ""Carrie""",0,3,female,NaN,W./C. 6607,23.4500,NaN,S,3
890,홀수,"Dooley, Mr. Patrick",0,3,male,32.0,370376,7.7500,NaN,Q,0

In [164]:
# 나이가 35 초과인 사람만 필터링
df[df['나이'] > 35]

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C
6,7,"McCarthy, Mr. Timothy J",0,1,male,54.0,17463,51.8625,E46,S
11,12,"Bonnell, Miss. Elizabeth",1,1,female,58.0,113783,26.5500,C103,S
13,14,"Andersson, Mr. Anders Johan",0,3,male,39.0,347082,31.2750,NaN,S
15,16,"Hewlett, Mrs. (Mary D Kingcome)",1,2,female,55.0,248706,16.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...
865,98,"Bystrom, Mrs. (Karolina)",1,2,female,42.0,236852,13.0000,NaN,S
871,104,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,female,47.0,11751,52.5542,D35,S
873,106,"Vander Cruyssen, Mr. Victor",0,3,male,47.0,345765,9.0000,NaN,S
879,112,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,female,56.0,11767,83.1583,C50,C
885,118,"Rice, Mrs. William (Margaret Norton)",0,3,female,39.0,382652,29.1250,NaN,Q

* 여성이면서 나이가 35세 초과인 행 찾기 and 조건

In [167]:
df[(df['성별'] == 'female') & (df['나이'] > 35)]

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C
11,12,"Bonnell, Miss. Elizabeth",1,1,female,58.0,113783,26.5500,C103,S
15,16,"Hewlett, Mrs. (Mary D Kingcome)",1,2,female,55.0,248706,16.0000,NaN,S
25,26,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",1,3,female,38.0,347077,31.3875,NaN,S
40,41,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",0,3,female,40.0,7546,9.4750,NaN,S
...,...,...,...,...,...,...,...,...,...,...
862,95,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",1,1,female,48.0,17466,25.9292,D17,S
865,98,"Bystrom, Mrs. (Karolina)",1,2,female,42.0,236852,13.0000,NaN,S
871,104,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",1,1,female,47.0,11751,52.5542,D35,S
879,112,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",1,1,female,56.0,11767,83.1583,C50,C
885,118,"Rice, Mrs. William (Margaret Norton)",0,3,female,39.0,382652,29.1250,NaN,Q

* 성별이 male, 선실등급 1, 생존여부 1인 사람을 찾으세요.

In [168]:
df[(df['성별'] == 'male') & (df['선실등급'] == 1) & (df['생존여부'] == 1)]

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
23,24,"Sloper, Mr. William Thompson",1,1,male,28.000000,113788,35.5000,A6,S
55,56,"Woolner, Mr. Hugh",1,1,male,NaN,19947,35.5000,C52,S
97,98,"Greenfield, Mr. William Bertram",1,1,male,23.000000,PC 17759,63.3583,D10 D12,C
187,-68,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",1,1,male,45.000000,111428,26.5500,NaN,S
209,-46,"Blank, Mr. Henry",1,1,male,40.000000,112277,31.0000,A31,C
224,-31,"Hoyt, Mr. Frederick Maxfield",1,1,male,38.000000,19943,90.0000,C93,S
248,-7,"Beckwith, Mr. Richard Leonard",1,1,male,37.000000,11751,52.5542,D35,S
298,43,"Saalfeld, Mr. Adolphe",1,1,male,NaN,19988,30.5000,C106,S
305,50,"Allison, Master. Hudson Trevor",1,1,male,0.919922,113781,151.5500,C22 C26,S
370,115,"Harder, Mr. George Achilles",1,1,male,25.000000,11765,55.4417,E50,C
390,-121,"Carter, Mr. William Ernest",1,1,male,36.000000,113760,120.0000,B96 B98,S
430,-81,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",1,1,male,28.000000,110564,26.5500,C52,S
445,-66,"Dodge, Master. Washington",1,1,male,4.000000,33638,81.8583,A34,S
447,-64,"Seward, Mr. Frederic Kimber",1,1,male,34.000000,113794,26.5500,NaN,S
449,-62,"Peuchen, Major. Arthur Godfrey",1,1,male,52.000000,113786,30.5000,C104,S
453,-58,"Goldenberg, Mr. Samuel L",1,1,male,49.000000,17453,89.1042,C92,C
460,-51,"Anderson, Mr. Harry",1,1,male,48.000000,19952,26.5500,E12,S
484,-27,"Bishop, Mr. Dickinson H",1,1,male,25.000000,11967,91.0792,B49,C
507,-4,"Bradley, Mr. George (""George Arthur Brayton"")",1,1,male,NaN,111427,26.5500,NaN,S
512,1,"McGough, Mr. James Robert",1,1,male,36.000000,PC 17473,26.2875,E25,S
550,39,"Thayer, Mr. John Borland Jr",1,1,male,17.000000,17421,110.8833,C70,C
572,61,"Flynn, Mr. John Irwin (""Irving"")",1,1,male,36.000000,PC 17474,26.3875,E25,S
587,76,"Frolicher-Stehli, Mr. Maxmillian",1,1,male,60.000000,13567,79.2000,B41,C
599,88,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",1,1,male,49.000000,PC 17485,56.9292,A20,C
604,93,"Homer, Mr. Harry (""Mr E Haven"")",1,1,male,35.000000,111426,26.5500,NaN,C
607,96,"Daniel, Mr. Robert Williams",1,1,male,27.000000,113804,30.5000,NaN,S
621,110,"Kimball, Mr. Edwin Nelson Jr",1,1,male,42.000000,11753,52.5542,D19,S
630,119,"Barkworth, Mr. Algernon Henry Wilson",1,1,male,80.000000,27042,30.0000,A23,S
632,121,"Stahelin-Maeglin, Dr. Max",1,1,male,32.000000,13214,30.5000,B50,C
645,-122,"Harper, Mr. Henry Sleeper",1,1,male,48.000000,PC 17572,76.7292,D33,C
647,-120,"Simonius-Blumer, Col. Oberst Alfons",1,1,male,56.000000,13213,35.5000,A26,C
660,-107,"Frauenthal, Dr. Henry William",1,1,male,50.000000,PC 17611,133.6500,NaN,S
679,-88,"Cardeza, Mr. Thomas Drake Martinez",1,1,male,36.000000,PC 17755,512.3292,B51 B53 B55,C
681,-86,"Hassab, Mr. Hammad",1,1,male,27.000000,PC 17572,76.7292,D49,C
690,-77,"Dick, Mr. Albert Adrian",1,1,male,31.000000,17474,57.0000,B20,S
701,-66,"Silverthorne, Mr. Spencer Victor",1,1,male,35.000000,PC 17475,26.2875,E24,S
707,-60,"Calderhead, Mr. Edward Pennington",1,1,male,42.000000,PC 17476,26.2875,E24,S
712,-55,"Taylor, Mr. Elmer Zebley",1,1,male,48.000000,19996,52.0000,C126,S
724,-43,"Chambers, Mr. Norman Campbell",1,1,male,27.000000,113806,53.1000,E8,S
737,-30,"Lesurer, Mr. Gustave J",1,1,male,35.000000,PC 17755,512.3292,B101,C
740,-27,"Hawksford, Mr. Walter James",1,1,male,NaN,16988,30.0000,D45,S
802,35,"Carter, Master. William Thornton II",1,1,male,11.000000,113760,120.0000,B96 B98,S
839,72,"Marechal, Mr. Pierre",1,1,male,NaN,11774,29.7000,C47,C
857,90,"Daly, Mr. Peter Denis",1,1,male,51.000000,113055,26.5500,E17,S
889,122,"Behr, Mr. Karl Howell",1,1,male,26.000000,111369,30.0000,C148,C

* 선실 등급별 승차권 금액의 최소, 최대, 평균 등 4분위수를 보고싶다.

In [170]:
# 선실 등급이 1등석인 사람들의 승차권 금액 통계량을 보고 싶다.
# df[df['선실등급'] == 1]['티켓가격'].describe()
df.loc[df['선실등급'] == 1, '티켓가격'].describe()

count    215.000000
mean      84.299128
std       78.534471
min        0.000000
25%       30.847900
50%       61.175000
75%       93.500000
max      512.329200
Name: 티켓가격, dtype: float64

In [176]:
df[df['티켓가격'] > 512]

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
258,3,"Ward, Miss. Anna",1,1,female,35.0,PC 17755,512.3292,NaN,C
679,-88,"Cardeza, Mr. Thomas Drake Martinez",1,1,male,36.0,PC 17755,512.3292,B51 B53 B55,C
737,-30,"Lesurer, Mr. Gustave J",1,1,male,35.0,PC 17755,512.3292,B101,C

In [177]:
df[df['티켓가격'] == 0]

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
179,-76,"Leonard, Mr. Lionel",0,3,male,36.0,LINE,0.0,NaN,S
263,8,"Harrison, Mr. William",0,1,male,40.0,112059,0.0,B94,S
271,16,"Tornquist, Mr. William Henry",1,3,male,25.0,LINE,0.0,NaN,S
277,22,"Parkes, Mr. Francis ""Frank""",0,2,male,NaN,239853,0.0,NaN,S
302,47,"Johnson, Mr. William Cahoone Jr",0,3,male,19.0,LINE,0.0,NaN,S
413,-98,"Cunningham, Mr. Alfred Fleming",0,2,male,NaN,239853,0.0,NaN,S
466,-45,"Campbell, Mr. William",0,2,male,NaN,239853,0.0,NaN,S
481,-30,"Frost, Mr. Anthony Wood ""Archie""",0,2,male,NaN,239854,0.0,NaN,S
597,86,"Johnson, Mr. Alfred",0,3,male,49.0,LINE,0.0,NaN,S
633,122,"Parr, Mr. William Henry Marsh",0,1,male,NaN,112052,0.0,NaN,S
674,-93,"Watson, Mr. Ennis Hastings",0,2,male,NaN,239856,0.0,NaN,S
732,-35,"Knight, Mr. Robert J",0,2,male,NaN,239855,0.0,NaN,S
806,39,"Andrews, Mr. Thomas Jr",0,1,male,39.0,112050,0.0,A36,S
815,48,"Fry, Mr. Richard",0,1,male,NaN,112058,0.0,B102,S
822,55,"Reuchlin, Jonkheer. John George",0,1,male,38.0,19972,0.0,NaN,S

#  조건에 맞는 행을 찾은 후 특정 컬럼만 조회하기

* 선실등급이 1이거나 2이면서 생존한 여성 중에서 이름 컬럼만 보고 싶을 때

In [224]:
df.columns

Index(['승객번호', '이름', '생존여부', '선실등급', '성별', '나이', '티켓번호', '티켓가격', '선실번호', '목적지',
       '가족수'],
      dtype='object')

In [179]:
df.loc[((df['선실등급'] == 1) | (df['선실등급'] == 2)) & (df['생존여부'] == 1) & (df['성별'] == 'female'), '이름']

일번     Cumings, Mrs. John Bradley (Florence Briggs Th...
9                    Nasser, Mrs. Nicholas (Adele Achem)
11                              Bonnell, Miss. Elizabeth
15                      Hewlett, Mrs. (Mary D Kingcome)
31        Spencer, Mrs. William Augustus (Marie Eugenie)
                             ...
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
874                Abelson, Mrs. Samuel (Hannah Wizosky)
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
880         Shelley, Mrs. William (Imanita Parrish Hall)
887                         Graham, Miss. Margaret Edith
Name: 이름, Length: 160, dtype: object

In [235]:
df[((df['선실등급'] == 1) | (df['선실등급'] == 2)) & (df['생존여부'] == 1) & (df['성별'] == 'female')]['이름']

1      Cumings, Mrs. John Bradley (Florence Briggs Th...
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
9                    Nasser, Mrs. Nicholas (Adele Achem)
11                              Bonnell, Miss. Elizabeth
15                      Hewlett, Mrs. (Mary D Kingcome)
                             ...
871     Beckwith, Mrs. Richard Leonard (Sallie Monypeny)
874                Abelson, Mrs. Samuel (Hannah Wizosky)
879        Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)
880         Shelley, Mrs. William (Imanita Parrish Hall)
887                         Graham, Miss. Margaret Edith
Name: 이름, Length: 161, dtype: object

* 나이가 25세 미만이면서 생존자의 이름

In [239]:
df.loc[(df['나이'] < 25) & (df['생존여부'] == 1), '이름']

9           Nasser, Mrs. Nicholas (Adele Achem)
10              Sandstrom, Miss. Marguerite Rut
22                  McGowan, Miss. Anna "Annie"
39                  Nicola-Yarred, Miss. Jamila
43     Laroche, Miss. Simonne Marie Anne Andree
                         ...
855                  Aks, Mrs. Sam (Leah Rosen)
858       Baclini, Mrs. Solomon (Latifa Qurban)
869             Johnson, Master. Harold Theodor
875            Najib, Miss. Adele Kiamie "Jane"
887                Graham, Miss. Margaret Edith
Name: 이름, Length: 118, dtype: object

In [240]:
# 결과에서 이름과 나이를 같이 보고 싶다.
df.loc[(df['나이'] < 25) & (df['생존여부'] == 1), ['이름', '나이']]

                                           이름    나이
9         Nasser, Mrs. Nicholas (Adele Achem)  14.0
10            Sandstrom, Miss. Marguerite Rut   4.0
22                McGowan, Miss. Anna "Annie"  15.0
39                Nicola-Yarred, Miss. Jamila  14.0
43   Laroche, Miss. Simonne Marie Anne Andree   3.0
..                                        ...   ...
855                Aks, Mrs. Sam (Leah Rosen)  18.0
858     Baclini, Mrs. Solomon (Latifa Qurban)  24.0
869           Johnson, Master. Harold Theodor   4.0
875          Najib, Miss. Adele Kiamie "Jane"  15.0
887              Graham, Miss. Margaret Edith  19.0

[118 rows x 2 columns]

In [184]:
df2 = df[(df.나이 < 25) & (df.생존여부 == 1)][["이름", "나이"]]
df2

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",1,2,female,14.0,237736,30.0708,NaN,C
10,11,"Sandstrom, Miss. Marguerite Rut",1,3,female,4.0,PP 9549,16.7000,G6,S
22,23,"McGowan, Miss. Anna ""Annie""",1,3,female,15.0,330923,8.0292,NaN,Q
39,40,"Nicola-Yarred, Miss. Jamila",1,3,female,14.0,2651,11.2417,NaN,C
43,44,"Laroche, Miss. Simonne Marie Anne Andree",1,2,female,3.0,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...
855,88,"Aks, Mrs. Sam (Leah Rosen)",1,3,female,18.0,392091,9.3500,NaN,S
858,91,"Baclini, Mrs. Solomon (Latifa Qurban)",1,3,female,24.0,2666,19.2583,NaN,C
869,102,"Johnson, Master. Harold Theodor",1,3,male,4.0,347742,11.1333,NaN,S
875,108,"Najib, Miss. Adele Kiamie ""Jane""",1,3,female,15.0,2667,7.2250,NaN,C
887,120,"Graham, Miss. Margaret Edith",1,1,female,19.0,112053,30.0000,B42,S

In [185]:
df2[["이름", "나이"]]

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

                                           이름    나이
9         Nasser, Mrs. Nicholas (Adele Achem)  14.0
10            Sandstrom, Miss. Marguerite Rut   4.0
22                McGowan, Miss. Anna "Annie"  15.0
39                Nicola-Yarred, Miss. Jamila  14.0
43   Laroche, Miss. Simonne Marie Anne Andree   3.0
..                                        ...   ...
855                Aks, Mrs. Sam (Leah Rosen)  18.0
858     Baclini, Mrs. Solomon (Latifa Qurban)  24.0
869           Johnson, Master. Harold Theodor   4.0
875          Najib, Miss. Adele Kiamie "Jane"  15.0
887              Graham, Miss. Margaret Edith  19.0

[118 rows x 2 columns]

In [244]:
df.나이

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: 나이, Length: 891, dtype: float64

.isin([조건1, 조건2]) or 조건을 여러 번 써야 할 때 간단히 표현

* 선실등급을 1, 2등인 사람을 추출

In [247]:
df[(df['선실등급'] == 1) | (df['선실등급'] == 2)]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,짝수,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C,1
3,짝수,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,1,female,35.0,113803,53.1000,C123,S,1
6,홀수,"McCarthy, Mr. Timothy J",0,1,male,54.0,17463,51.8625,E46,S,0
9,짝수,"Nasser, Mrs. Nicholas (Adele Achem)",1,2,female,14.0,237736,30.0708,NaN,C,1
11,짝수,"Bonnell, Miss. Elizabeth",1,1,female,58.0,113783,26.5500,C103,S,0
...,...,...,...,...,...,...,...,...,...,...,...
880,홀수,"Shelley, Mrs. William (Imanita Parrish Hall)",1,2,female,25.0,230433,26.0000,NaN,S,1
883,짝수,"Banfield, Mr. Frederick James",0,2,male,28.0,C.A./SOTON 34068,10.5000,NaN,S,0
886,홀수,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S,0
887,짝수,"Graham, Miss. Margaret Edith",1,1,female,19.0,112053,30.0000,B42,S,0
889,짝수,"Behr, Mr. Karl Howell",1,1,male,26.0,111369,30.0000,C148,C,0

In [186]:
df[df['선실등급'].isin([1,2])]

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
일번,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C
6,7,"McCarthy, Mr. Timothy J",0,1,male,54.0,17463,51.8625,E46,S
9,10,"Nasser, Mrs. Nicholas (Adele Achem)",1,2,female,14.0,237736,30.0708,NaN,C
11,12,"Bonnell, Miss. Elizabeth",1,1,female,58.0,113783,26.5500,C103,S
15,16,"Hewlett, Mrs. (Mary D Kingcome)",1,2,female,55.0,248706,16.0000,NaN,S
...,...,...,...,...,...,...,...,...,...,...
880,113,"Shelley, Mrs. William (Imanita Parrish Hall)",1,2,female,25.0,230433,26.0000,NaN,S
883,116,"Banfield, Mr. Frederick James",0,2,male,28.0,C.A./SOTON 34068,10.5000,NaN,S
886,119,"Montvila, Rev. Juozas",0,2,male,27.0,211536,13.0000,NaN,S
887,120,"Graham, Miss. Margaret Edith",1,1,female,19.0,112053,30.0000,B42,S
889,122,"Behr, Mr. Karl Howell",1,1,male,26.0,111369,30.0000,C148,C

# 특정 단어를 포함한 행 찾기
* 이름에 Joseph 가 들어간 사람 찾기
* like %단어% - SQL
* .str.contains("찾을 단어")

In [189]:
df[df['이름'] == "Joseph"]

Empty DataFrame
Columns: [승객번호, 이름, 생존여부, 선실등급, 성별, 나이, 티켓번호, 티켓가격, 선실번호, 목적지]
Index: []

In [190]:
df[df['이름'].str.contains("Joseph")]

C:\Users\haram\miniforge3\envs\fintech\lib\site-packages\pandas\io\formats\format.py:1458: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지
20,21,"Fynney, Mr. Joseph J",0,2,male,35.0,239865,26.0000,NaN,S
34,35,"Meyer, Mr. Edgar Joseph",0,1,male,28.0,PC 17604,82.1708,NaN,C
95,96,"Shorney, Mr. Charles Joseph",0,3,male,NaN,374910,8.0500,NaN,S
140,-115,"Boulos, Mrs. Joseph (Sultana)",0,3,female,NaN,2678,15.2458,NaN,C
145,-110,"Nicholls, Mr. Joseph Charles",0,2,male,19.0,C.A. 33112,36.7500,NaN,S
194,-61,"Brown, Mrs. James Joseph (Margaret Tobin)",1,1,female,44.0,PC 17610,27.7208,B4,C
375,120,"Meyer, Mrs. Edgar Joseph (Leila Saks)",1,1,female,NaN,PC 17604,82.1708,NaN,C
454,-57,"Peduzzi, Mr. Joseph",0,3,male,NaN,A/5 2817,8.0500,NaN,S
532,21,"Elias, Mr. Joseph Jr",0,3,male,17.0,2690,7.2292,NaN,C
559,48,"de Messemaeker, Mrs. Guillaume Joseph (Emma)",1,3,female,36.0,345572,17.4000,NaN,S
578,67,"Caram, Mrs. Joseph (Maria Elias)",0,3,female,NaN,2689,14.4583,NaN,C
589,78,"Murdlin, Mr. Joseph",0,3,male,NaN,A./5. 3235,8.0500,NaN,S
608,97,"Laroche, Mrs. Joseph (Juliette Marie Louise La...",1,2,female,22.0,SC/Paris 2123,41.5792,NaN,C
685,-82,"Laroche, Mr. Joseph Philippe Lemercier",0,2,male,25.0,SC/Paris 2123,41.5792,NaN,C
752,-15,"Vande Velde, Mr. Johannes Joseph",0,3,male,33.0,345780,9.5000,NaN,S
828,61,"McCormack, Mr. Thomas Joseph",1,3,male,NaN,367228,7.7500,NaN,Q

In [256]:
# 티켓번호에 PC라는 문자가 포함된 티켓을 필터링
df[df['티켓번호'].str.contains("PC")]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
1,짝수,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,1,female,38.0,PC 17599,71.2833,C85,C,1
30,홀수,"Uruchurtu, Don. Manuel E",0,1,male,40.0,PC 17601,27.7208,NaN,C,0
31,짝수,"Spencer, Mrs. William Augustus (Marie Eugenie)",1,1,female,NaN,PC 17569,146.5208,B78,C,1
34,홀수,"Meyer, Mr. Edgar Joseph",0,1,male,28.0,PC 17604,82.1708,NaN,C,1
52,홀수,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",1,1,female,49.0,PC 17572,76.7292,D33,C,1
64,홀수,"Stewart, Mr. Albert A",0,1,male,NaN,PC 17605,27.7208,NaN,C,0
96,홀수,"Goldschmidt, Mr. George B",0,1,male,71.0,PC 17754,34.6542,A5,C,0
97,짝수,"Greenfield, Mr. William Bertram",1,1,male,23.0,PC 17759,63.3583,D10 D12,C,1
118,홀수,"Baxter, Mr. Quigg Edmond",0,1,male,24.0,PC 17558,247.5208,B58 B60,C,1
139,짝수,"Giglio, Mr. Victor",0,1,male,24.0,PC 17593,79.2000,B86,C,0
155,짝수,"Williams, Mr. Charles Duane",0,1,male,51.0,PC 17597,61.3792,NaN,C,1
168,홀수,"Baumann, Mr. John D",0,1,male,NaN,PC 17318,25.9250,NaN,S,0
177,짝수,"Isham, Miss. Ann Elizabeth",0,1,female,50.0,PC 17595,28.7125,C49,C,0
194,홀수,"Brown, Mrs. James Joseph (Margaret Tobin)",1,1,female,44.0,PC 17610,27.7208,B4,C,0
195,짝수,"Lurette, Miss. Elise",1,1,female,58.0,PC 17569,146.5208,B80,C,0
256,홀수,"Thorne, Mrs. Gertrude Maybelle",1,1,female,NaN,PC 17585,79.2000,NaN,C,0
258,홀수,"Ward, Miss. Anna",1,1,female,35.0,PC 17755,512.3292,NaN,C,0
268,홀수,"Graham, Mrs. William Thompson (Edith Junkins)",1,1,female,58.0,PC 17582,153.4625,C125,S,1
269,짝수,"Bissette, Miss. Amelia",1,1,female,35.0,PC 17760,135.6333,C99,S,0
273,짝수,"Natsch, Mr. Charles H",0,1,male,37.0,PC 17596,29.7000,C118,C,1
295,짝수,"Lewy, Mr. Ervin G",0,1,male,NaN,PC 17612,27.7208,NaN,C,0
299,짝수,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",1,1,female,50.0,PC 17558,247.5208,B58 B60,C,1
307,짝수,"Penasco y Castellana, Mrs. Victor de Satode (M...",1,1,female,17.0,PC 17758,108.9000,C65,C,1
309,짝수,"Francatelli, Miss. Laura Mabel",1,1,female,30.0,PC 17485,56.9292,E36,C,0
311,짝수,"Ryerson, Miss. Emily Borie",1,1,female,18.0,PC 17608,262.3750,B57 B59 B63 B66,C,4
325,짝수,"Young, Miss. Marie Grice",1,1,female,36.0,PC 17760,135.6333,C32,C,0
332,홀수,"Graham, Mr. George Edward",0,1,male,38.0,PC 17582,153.4625,C91,S,1
334,홀수,"Frauenthal, Mrs. Henry William (Clara Heinshei...",1,1,female,NaN,PC 17611,133.6500,NaN,S,1
369,짝수,"Aubart, Mme. Leontine Pauline",1,1,female,24.0,PC 17477,69.3000,B35,C,0
373,짝수,"Ringhini, Mr. Sante",0,1,male,22.0,PC 17760,135.6333,NaN,C,0
375,짝수,"Meyer, Mrs. Edgar Joseph (Leila Saks)",1,1,female,NaN,PC 17604,82.1708,NaN,C,1
380,홀수,"Bidois, Miss. Rosalie",1,1,female,42.0,PC 17757,227.5250,NaN,C,0
493,짝수,"Artagaveytia, Mr. Ramon",0,1,male,71.0,PC 17609,49.5042,NaN,C,0
505,짝수,"Penasco y Castellana, Mr. Victor de Satode",0,1,male,18.0,PC 17758,108.9000,C65,C,1
512,홀수,"McGough, Mr. James Robert",1,1,male,36.0,PC 17473,26.2875,E25,S,0
513,짝수,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",1,1,female,54.0,PC 17603,59.4000,NaN,C,1
527,짝수,"Farthing, Mr. John",0,1,male,NaN,PC 17483,221.7792,C95,S,0
537,짝수,"LeRoy, Miss. Bertha",1,1,female,30.0,PC 17761,106.4250,NaN,C,0
544,홀수,"Douglas, Mr. Walter Donald",0,1,male,50.0,PC 17761,106.4250,C86,C,1
557,짝수,"Robbins, Mr. Victor",0,1,male,NaN,PC 17757,227.5250,NaN,C,0
572,홀수,"Flynn, Mr. John Irwin (""Irving"")",1,1,male,36.0,PC 17474,26.3875,E25,S,0
599,짝수,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",1,1,male,49.0,PC 17485,56.9292,A20,C,1
609,짝수,"Shutes, Miss. Elizabeth W",1,1,female,40.0,PC 17582,153.4625,C125,S,0
641,짝수,"Sagesser, Mlle. Emma",1,1,female,24.0,PC 17477,69.3000,B35,C,0
645,짝수,"Harper, Mr. Henry Sleeper",1,1,male,48.0,PC 17572,76.7292,D33,C,1
660,홀수,"Frauenthal, Dr. Henry William",1,1,male,50.0,PC 17611,133.6500,NaN,S,2
679,짝수,"Cardeza, Mr. Thomas Drake Martinez",1,1,male,36.0,PC 17755,512.3292,B51 B53 B55,C,1
681,짝수,"Hassab, Mr. Hammad",1,1,male,27.0,PC 17572,76.7292,D49,C,0
700,홀수,"Astor, Mrs. John Jacob (Madeleine Talmadge Force)",1,1,female,18.0,PC 17757,227.5250,C62 C64,C,1
701,짝수,"Silverthorne, Mr. Spencer Victor",1,1,male,35.0,PC 17475,26.2875,E24,S,0
707,짝수,"Calderhead, Mr. Edward Pennington",1,1,male,42.0,PC 17476,26.2875,E24,S,0
710,홀수,"Mayne, Mlle. Berthe Antonine (""Mrs de Villiers"")",1,1,female,24.0,PC 17482,49.5042,C90,C,0
716,홀수,"Endres, Miss. Caroline Louise",1,1,female,38.0,PC 17757,227.5250,C45,C,0
737,짝수,"Lesurer, Mr. Gustave J",1,1,male,35.0,PC 17755,512.3292,B101,C,0
742,홀수,"Ryerson, Miss. Susan Parker ""Suzette""",1,1,female,21.0,PC 17608,262.3750,B57 B59 B63 B66,C,4
789,짝수,"Guggenheim, Mr. Benjamin",0,1,male,46.0,PC 17593,79.2000,B82 B84,C,0
793,짝수,"Hoyt, Mr. William Fisher",0,1,male,NaN,PC 17600,30.6958,NaN,C,0
835,짝수,"Compton, Miss. Sara Rebecca",1,1,female,39.0,PC 17756,83.1583,E49,C,2
853,짝수,"Lines, Miss. Mary Conover",1,1,female,16.0,PC 17592,39.4000,D28,S,1
867,짝수,"Roebling, Mr. Washington Augustus II",0,1,male,31.0,PC 17590,50.4958,A24,S,0

In [257]:
df[df['티켓번호'].str.contains("C.A")]

,승객번호,이름,생존여부,선실등급,성별,나이,티켓번호,티켓가격,선실번호,목적지,가족수
33,짝수,"Wheadon, Mr. Edward H",0,2,male,66.0,C.A. 24579,10.5000,NaN,S,0
56,홀수,"Rugg, Miss. Emily",1,2,female,21.0,C.A. 31026,10.5000,NaN,S,0
58,홀수,"West, Miss. Constance Mirium",1,2,female,5.0,C.A. 34651,27.7500,NaN,S,3
66,홀수,"Nye, Mrs. (Elizabeth Ramell)",1,2,female,29.0,C.A. 29395,10.5000,F33,S,0
70,홀수,"Jenkin, Mr. Stephen Curnow",0,2,male,32.0,C.A. 33111,10.5000,NaN,S,0
93,짝수,"Dean, Mr. Bertram Frank",0,3,male,26.0,C.A. 2315,20.5750,NaN,S,3
134,홀수,"Sobey, Mr. Samuel James Hayden",0,2,male,25.0,C.A. 29178,13.0000,NaN,S,0
145,짝수,"Nicholls, Mr. Joseph Charles",0,2,male,19.0,C.A. 33112,36.7500,NaN,S,2
161,짝수,"Watt, Mrs. James (Elizabeth ""Bessie"" Inglis Mi...",1,2,female,40.0,C.A. 33595,15.7500,NaN,S,0
234,홀수,"Leyson, Mr. Robert William Norman",0,2,male,24.0,C.A. 29566,10.5000,NaN,S,0
237,짝수,"Collyer, Miss. Marjorie ""Lottie""",1,2,female,8.0,C.A. 31921,26.2500,NaN,S,2
265,짝수,"Reeves, Mr. David",0,2,male,36.0,C.A. 17248,10.5000,NaN,S,0
279,짝수,"Abbott, Mrs. Stanton (Rosa Hunt)",1,3,female,35.0,C.A. 2673,20.2500,NaN,S,2
348,홀수,"Coutts, Master. William Loch ""William""",1,3,male,3.0,C.A. 37671,15.9000,NaN,S,2
432,홀수,"Louch, Mrs. Charles Alexander (Alice Adelaide ...",1,2,female,42.0,SC/AH 3085,26.0000,NaN,S,1
439,짝수,"Kvillner, Mr. Johan Henrik Johannesson",0,2,male,31.0,C.A. 18723,10.5000,NaN,S,0
450,홀수,"West, Mr. Edwy Arthur",0,2,male,36.0,C.A. 34651,27.7500,NaN,S,3
472,홀수,"West, Mrs. Edwy Arthur (Ada Mary Worth)",1,2,female,33.0,C.A. 34651,27.7500,NaN,S,3
473,짝수,"Jerwan, Mrs. Amin S (Marie Marthe Thuillard)",1,2,female,23.0,SC/AH Basle 541,13.7917,D,C,0
489,짝수,"Coutts, Master. Eden Leslie ""Neville""",1,3,male,9.0,C.A. 37671,15.9000,NaN,S,2
497,짝수,"Shellard, Mr. Frederick William",0,3,male,NaN,C.A. 6212,15.1000,NaN,S,0
516,홀수,"Lemore, Mrs. (Amelia Milley)",1,2,female,34.0,C.A. 34260,10.5000,F33,S,0
549,짝수,"Davies, Master. John Morgan Jr",1,2,male,8.0,C.A. 33112,36.7500,NaN,S,2
594,홀수,"Chapman, Mr. John Henry",0,2,male,37.0,SC/AH 29037,26.0000,NaN,S,1
637,짝수,"Collyer, Mr. Harvey",0,2,male,31.0,C.A. 31921,26.2500,NaN,S,2
672,홀수,"Mitchell, Mr. Henry Michael",0,2,male,70.0,C.A. 24580,10.5000,NaN,S,0
746,홀수,"Abbott, Mr. Rossmore Edward",0,3,male,16.0,C.A. 2673,20.2500,NaN,S,2
788,홀수,"Dean, Master. Bertram Vere",1,3,male,1.0,C.A. 2315,20.5750,NaN,S,3
801,짝수,"Collyer, Mrs. Harvey (Charlotte Annie Tate)",1,2,female,31.0,C.A. 31921,26.2500,NaN,S,2
845,짝수,"Abbing, Mr. Anthony",0,3,male,42.0,C.A. 5547,7.5500,NaN,S,0
883,짝수,"Banfield, Mr. Frederick James",0,2,male,28.0,C.A./SOTON 34068,10.5000,NaN,S,0

* 승객이름에서 () 없애기
* 반복문/리스표현식을 이용해 없애기
* apply+ lambda 함수를 이용해 없애기
* .str 메서드를 이용해서 없애기

* 반복문 이용하기

In [205]:
result = []
for name in df['이름']:
#     print(name, type(name))
    result.append(name.replace("(", "").replace(")", ""))
result
df['이름'] = result

In [215]:
# df

apply와 lambda 함수를 이용해 작업하기

In [208]:
df2 = df.copy()

In [210]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [221]:
%%time
df['Name'].apply(lambda name: name.replace("(", "").replace(")", ""))

CPU times: total: 0 ns
Wall time: 0 ns

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley Florence Briggs Thayer
2                                 Heikkinen, Miss. Laina
3             Futrelle, Mrs. Jacques Heath Lily May Peel
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

.str.replace를 활용해서 처리하기

In [220]:
%%time
df['Name'].str.replace("(", "").str.replace(")", "")

CPU times: total: 0 ns
Wall time: 1.03 ms

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley Florence Briggs Thayer
2                                 Heikkinen, Miss. Laina
3             Futrelle, Mrs. Jacques Heath Lily May Peel
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

.str.문자열함수 (upper, lower, split, join, strip)

In [225]:
print(type(df['Name']))
print(type(df['Name'][0]))

<class 'pandas.core.series.Series'>
<class 'str'>

In [232]:
df['Name'] = df['Name'].str.split(" ")

In [237]:
df['Name'] = df['Name'].str.join(" ")

In [238]:
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [242]:
df['Name'] = df['Name'].str.split(", ")

In [246]:
df['first_name'] = df['Name'].apply(lambda x: x[0])
df['second_name'] = df['Name'].apply(lambda x: x[1])

In [247]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name,second_name
0,1,0,3,"[Braund, Mr. Owen Harris]",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Braund,Mr. Owen Harris
1,2,1,1,"[Cumings, Mrs. John Bradley (Florence Briggs T...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
2,3,1,3,"[Heikkinen, Miss. Laina]",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Heikkinen,Miss. Laina
3,4,1,1,"[Futrelle, Mrs. Jacques Heath (Lily May Peel)]",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel)
4,5,0,3,"[Allen, Mr. William Henry]",male,35.0,0,0,373450,8.0500,NaN,S,Allen,Mr. William Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"[Montvila, Rev. Juozas]",male,27.0,0,0,211536,13.0000,NaN,S,Montvila,Rev. Juozas
887,888,1,1,"[Graham, Miss. Margaret Edith]",female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss. Margaret Edith
888,889,0,3,"[Johnston, Miss. Catherine Helen ""Carrie""]",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Johnston,"Miss. Catherine Helen ""Carrie"""
889,890,1,1,"[Behr, Mr. Karl Howell]",male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr. Karl Howell
890,891,0,3,"[Dooley, Mr. Patrick]",male,32.0,0,0,370376,7.7500,NaN,Q,Dooley,Mr. Patrick

# groupby
* 특정 기준 컬럼 지정해서 다른 컬럼의 통계량 (평균, 최소, 최대)
* df[['보고싶은 컬럼1','보고싶은컬럼2']].groupby('기준컬럼').집합함수(mean, max, min, median, count)

In [248]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'first_name',
       'second_name'],
      dtype='object')

* 성별별 생존자 수

In [260]:
survbysex = df[['Sex', 'Survived']].groupby(['Sex']).value_counts(sort=False)
survbysex

Sex     Survived
female  0            81
        1           233
male    0           468
        1           109
Name: count, dtype: int64

In [264]:
print(type(survbysex))

<class 'pandas.core.series.Series'>

In [265]:
survbysex.index

MultiIndex([('female', 0),
            ('female', 1),
            (  'male', 0),
            (  'male', 1)],
           names=['Sex', 'Survived'])

In [266]:
df3 = pd.DataFrame(survbysex)
df3

                 count
Sex    Survived
female 0            81
       1           233
male   0           468
       1           109

In [268]:
233 / (81+233) * 100

74.20382165605095

In [269]:
109 / (109+468) * 100

18.890814558058924

선실등급별 생존자 수

In [270]:
df[['Pclass', 'Survived']].groupby('Pclass').value_counts(sort=False)

Pclass  Survived
1       0            80
        1           136
2       0            97
        1            87
3       0           372
        1           119
Name: count, dtype: int64

성별별, 선실등급 별 생존자수

In [273]:
df[['Sex', 'Pclass', 'Survived']].groupby(['Sex', 'Pclass']).value_counts(sort=False)

Sex     Pclass  Survived
female  1       0             3
                1            91
        2       0             6
                1            70
        3       0            72
                1            72
male    1       0            77
                1            45
        2       0            91
                1            17
        3       0           300
                1            47
Name: count, dtype: int64

은행 고객 등급
- 급여 통장 입금여부, 액수
- 적금, 예금

* 성별에 따른 나이의 평균, 최소, 최대값

In [274]:
df[['Sex', 'Age']].groupby('Sex').mean()

              Age
Sex
female  27.915709
male    30.726645

In [275]:
df[['Sex', 'Age']].groupby('Sex').min()

         Age
Sex
female  0.75
male    0.42

In [276]:
df[['Sex', 'Age']].groupby('Sex').max()

         Age
Sex
female  63.0
male    80.0

In [277]:
df[['Sex', 'Age']].groupby('Sex').describe()

          Age
        count       mean        std   min   25%   50%   75%   max
Sex
female  261.0  27.915709  14.110146  0.75  18.0  27.0  37.0  63.0
male    453.0  30.726645  14.678201  0.42  21.0  29.0  39.0  80.0

In [281]:
df[['Sex', 'Age']].groupby('Sex').agg(['min', 'max', 'mean'])

         Age
         min   max       mean
Sex
female  0.75  63.0  27.915709
male    0.42  80.0  30.726645

* 피벗테이블 pivot

In [284]:
df.pivot_table(values="Survived", index='Sex', columns="Pclass")

Pclass         1         2         3
Sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

# 결측값 찾기( 값이 없는 것)

In [285]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
 12  first_name   891 non-null    object
 13  second_name  891 non-null    object
dtypes: float64(2), int64(5), object(7)
memory usage: 97.6+ KB

In [288]:
len(df)

891

isna() 결측값인지 아닌지 확인 -> True(1), Flase(0) -> sum(결측값의 개수)

In [289]:
df.isna().sum() / len(df) * 100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
first_name      0.000000
second_name     0.000000
dtype: float64

dropna() 결측값이 있는 행을 삭제

In [290]:
df.dropna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,first_name,second_name
1,2,1,1,"[Cumings, Mrs. John Bradley (Florence Briggs T...",female,38.0,1,0,PC 17599,71.2833,C85,C,Cumings,Mrs. John Bradley (Florence Briggs Thayer)
3,4,1,1,"[Futrelle, Mrs. Jacques Heath (Lily May Peel)]",female,35.0,1,0,113803,53.1000,C123,S,Futrelle,Mrs. Jacques Heath (Lily May Peel)
6,7,0,1,"[McCarthy, Mr. Timothy J]",male,54.0,0,0,17463,51.8625,E46,S,McCarthy,Mr. Timothy J
10,11,1,3,"[Sandstrom, Miss. Marguerite Rut]",female,4.0,1,1,PP 9549,16.7000,G6,S,Sandstrom,Miss. Marguerite Rut
11,12,1,1,"[Bonnell, Miss. Elizabeth]",female,58.0,0,0,113783,26.5500,C103,S,Bonnell,Miss. Elizabeth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"[Beckwith, Mrs. Richard Leonard (Sallie Monype...",female,47.0,1,1,11751,52.5542,D35,S,Beckwith,Mrs. Richard Leonard (Sallie Monypeny)
872,873,0,1,"[Carlsson, Mr. Frans Olof]",male,33.0,0,0,695,5.0000,B51 B53 B55,S,Carlsson,Mr. Frans Olof
879,880,1,1,"[Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)]",female,56.0,0,1,11767,83.1583,C50,C,Potter,Mrs. Thomas Jr (Lily Alexenia Wilson)
887,888,1,1,"[Graham, Miss. Margaret Edith]",female,19.0,0,0,112053,30.0000,B42,S,Graham,Miss. Margaret Edith
889,890,1,1,"[Behr, Mr. Karl Howell]",male,26.0,0,0,111369,30.0000,C148,C,Behr,Mr. Karl Howell

fillna() 결측값을 다른 값으로 채워주는 함수

In [292]:
round(df['Age'].mean())

30

In [294]:
df['Age'] = df['Age'].fillna(round(df['Age'].mean()))

In [296]:
df['Age'].isna().sum()

np.int64(0)

# 여러개의 데이터프레임 합치기
* concat: 두 개의 데이터 프레임을 1개로 합침 
* merge: sql join과 같은 역할 공통된 기준 컬럼 매칭해서 합침
* join: sql join과 같은 역할 index가 같은 것 끼리 합침

In [297]:
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb

In [299]:
engine = create_engine("mysql+pymysql://kict20:kict20@221.155.18.165:3306/titanic")
conn = engine.connect()

In [300]:
passenger = pd.read_sql("p_info", con=conn)
ticket = pd.read_sql("t_info", con=conn)
survived = pd.read_sql("survived", con=conn)
conn.close()

In [302]:
passenger.head(1)

   PassengerId                     Name   Sex   Age  SibSp  Parch
0            1  Braund, Mr. Owen Harris  male  22.0      1      0

In [303]:
ticket.head(1)

   PassengerId     Ticket  Pclass  Fare Cabin Embarked
0            1  A/5 21171       3  7.25  None        S

In [304]:
survived.head(1)

   PassengerId  Survived
0            1         0

## concat  axis=0 행 추가, axis=1 열 추가
* 기준 컬럼 없이 무조건 합침
* 기본값은 행방향으로 합쳐줌
* 옆으로 붙이고 싶으면 axis=1

In [310]:
print("passenger", passenger.shape)
print("ticket", ticket.shape)
print("survived", survived.shape)

passenger (891, 6)
ticket (891, 6)
survived (891, 2)

In [314]:
df_0 = pd.concat([passenger, ticket, survived], axis=0)
df_0.iloc[890:893, :]
df_0

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
2,3,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
4,5,"Allen, Mr. William Henry",male,35.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
887,888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
888,889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0
889,890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
890,891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [308]:
df1 = pd.concat([passenger, ticket, survived], axis=1)
df1

,PassengerId,Name,Sex,Age,SibSp,Parch,PassengerId,Ticket,Pclass,Fare,Cabin,Embarked,PassengerId,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,1,A/5 21171,3,7.2500,None,S,1,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,2,PC 17599,1,71.2833,C85,C,2,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,3,STON/O2. 3101282,3,7.9250,None,S,3,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,4,113803,1,53.1000,C123,S,4,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,5,373450,3,8.0500,None,S,5,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,887,211536,2,13.0000,None,S,887,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,888,112053,1,30.0000,B42,S,888,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,889,W./C. 6607,3,23.4500,None,S,889,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,890,111369,1,30.0000,C148,C,890,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,891,370376,3,7.7500,None,Q,891,0

In [315]:
passenger.head(1)

   PassengerId                     Name   Sex   Age  SibSp  Parch
0            1  Braund, Mr. Owen Harris  male  22.0      1      0

In [316]:
ticket.head(1)

   PassengerId     Ticket  Pclass  Fare Cabin Embarked
0            1  A/5 21171       3  7.25  None        S

# merge: sql의 join문과 같음

In [318]:
# select * from passenger left join ticket on passenger.PassengerId = ticket.PassengerId
joined_df = pd.merge(passenger, ticket, how="inner", on="PassengerId")

In [321]:
joined_df = pd.merge(joined_df, survived, how='inner', on='PassengerId')
joined_df

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0

# join: sql의 join과 같음, index명을 기준으로 합침

In [331]:
passenger = passenger.set_index("PassengerId")

In [332]:
passenger

,Name,Sex,Age,SibSp,Parch
PassengerId,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0
3,"Heikkinen, Miss. Laina",female,26.0,0,0
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0
5,"Allen, Mr. William Henry",male,35.0,0,0
...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.0,0,0
888,"Graham, Miss. Margaret Edith",female,19.0,0,0
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2
890,"Behr, Mr. Karl Howell",male,26.0,0,0
891,"Dooley, Mr. Patrick",male,32.0,0,0

In [334]:
ticket = ticket.set_index("PassengerId")
ticket

                       Ticket  Pclass     Fare Cabin Embarked
PassengerId
1                   A/5 21171       3   7.2500  None        S
2                    PC 17599       1  71.2833   C85        C
3            STON/O2. 3101282       3   7.9250  None        S
4                      113803       1  53.1000  C123        S
5                      373450       3   8.0500  None        S
...                       ...     ...      ...   ...      ...
887                    211536       2  13.0000  None        S
888                    112053       1  30.0000   B42        S
889                W./C. 6607       3  23.4500  None        S
890                    111369       1  30.0000  C148        C
891                    370376       3   7.7500  None        Q

[891 rows x 5 columns]

In [336]:
joined_df2 = passenger.join(ticket)
joined_df2

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S
...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S
888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S
890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C
891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q

In [338]:
survived = survived.set_index("PassengerId")
survived

             Survived
PassengerId
1                   0
2                   1
3                   1
4                   1
5                   0
...               ...
887                 0
888                 1
889                 0
890                 1
891                 0

[891 rows x 1 columns]

In [340]:
joined_df2 = joined_df2.join(survived)
joined_df2

,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
PassengerId,,,,,,,,,,,
1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
...,...,...,...,...,...,...,...,...,...,...,...
887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0
888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1
889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0
890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1
891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0

In [342]:
joined_df2 = joined_df2.reset_index()
joined_df2

,PassengerId,Name,Sex,Age,SibSp,Parch,Ticket,Pclass,Fare,Cabin,Embarked,Survived
0,1,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,3,7.2500,None,S,0
1,2,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,1,71.2833,C85,C,1
2,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,3,7.9250,None,S,1
3,4,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,1,53.1000,C123,S,1
4,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,3,8.0500,None,S,0
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,"Montvila, Rev. Juozas",male,27.0,0,0,211536,2,13.0000,None,S,0
887,888,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,1,30.0000,B42,S,1
888,889,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,3,23.4500,None,S,0
889,890,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,1,30.0000,C148,C,1
890,891,"Dooley, Mr. Patrick",male,32.0,0,0,370376,3,7.7500,None,Q,0

# 중복여부 확인 및 제거하기

In [345]:
toss = pd.read_csv("./data/toss_reviews.csv", index_col=0)
toss.head(5)

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
1,최유연,5,"증권부분이 너무 빈약해요. 이평선, 분봉, 틱봉 자유롭게 수치를 설정할 수 있었음 ...",2025년 1월 18일,"안녕하세요. 최유연 님, 토스팀입니다. 토스증권 사용하시면서 주신 소중한 의견 너무..."
2,EXPRESS,5,주식 UI에서 홈과 관심 종목을 나눈 것도 불편한데 이번 자주 사용하는 계좌 업데이...,2025년 2월 25일,"안녕하세요. EXPRESS 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄..."
3,JS P,5,언제 한 번 대대적으로 앱 퍼포먼스 최적화를 했으면 좋겠습니다. 예전엔 이러지 않았...,2025년 2월 28일,"안녕하세요. JS P 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였..."
4,AndPeter,5,앱 최적화 좀 해주세요! 무슨 메모리를 1GB나 잡아먹고 패킷전송이 하루에 80만건...,2025년 3월 1일,"안녕하세요. AndPeter 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."

In [346]:
toss.info()

<class 'pandas.core.frame.DataFrame'>
Index: 57228 entries, 0 to 57227
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사용자     57185 non-null  object
 1   별점      57228 non-null  int64
 2   리뷰      57228 non-null  object
 3   날짜      57228 non-null  object
 4   개발자 응답  54031 non-null  object
dtypes: int64(1), object(4)
memory usage: 2.6+ MB

In [348]:
toss[toss["사용자"] == "Won Choi"]

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
20,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
40,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
60,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
80,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
...,...,...,...,...,...
54642,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
55156,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
55670,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
56184,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
56698,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."

In [353]:
toss.duplicated().sum()

np.int64(56698)

중복 컬럼 삭제하기 drop_duplicates()

In [355]:
toss = toss.drop_duplicates()
toss

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
1,최유연,5,"증권부분이 너무 빈약해요. 이평선, 분봉, 틱봉 자유롭게 수치를 설정할 수 있었음 ...",2025년 1월 18일,"안녕하세요. 최유연 님, 토스팀입니다. 토스증권 사용하시면서 주신 소중한 의견 너무..."
2,EXPRESS,5,주식 UI에서 홈과 관심 종목을 나눈 것도 불편한데 이번 자주 사용하는 계좌 업데이...,2025년 2월 25일,"안녕하세요. EXPRESS 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄..."
3,JS P,5,언제 한 번 대대적으로 앱 퍼포먼스 최적화를 했으면 좋겠습니다. 예전엔 이러지 않았...,2025년 2월 28일,"안녕하세요. JS P 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였..."
4,AndPeter,5,앱 최적화 좀 해주세요! 무슨 메모리를 1GB나 잡아먹고 패킷전송이 하루에 80만건...,2025년 3월 1일,"안녕하세요. AndPeter 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
...,...,...,...,...,...
57223,김민,5,"아니 업데이트 방금하니까, 주문수정하는게 가격 바꾸는게 안되네요? 무조건 취소하고 ...",2024년 11월 11일,"안녕하세요 김민님, 토스팀입니다. 우선 토스증권 서비스 이용에 불편을 드려 정말 죄..."
57224,최고운,5,업데이트 후 동영상 재생광고를 선택권없이 무조건 시청해야 하군요. wi-fi 환경이...,2023년 6월 3일,"안녕하세요. 최고운님. 토스 고객센터입니다. 먼저, 이용에 불편을 드려 죄송합니다...."
57225,블리,5,"라이브쇼핑보고,포인트받기 시스템 변경후,어찌 주구장창 1포인트만 나오는지.........",2024년 4월 11일,"안녕하세요. 블리님, 토스 고객센터입니다. 먼저 서비스 이용에 불편을 드렸다면 대단..."
57226,조명현,5,구석구석 숨어있던 버그를 잡다가 업데이트 설치가 안 되는 버그가 생긴 듯 합니다,2025년 2월 25일,"안녕하세요. 조명현 님, 토스팀입니다. 사용에 불편을 드린것 같아 마음이 무겁습니다..."
57227,이예진,5,홈화면에 계좌 순서 설정한게 반영 안되게 바뀌었는지 이해가 안감 너무 불편함,2025년 2월 27일,"안녕하세요. 이예진 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주..."

In [356]:
toss = toss.reset_index(drop=True)
toss

,사용자,별점,리뷰,날짜,개발자 응답
0,Won Choi,5,토스 많이 이용하는데 나쁘지 않음. 하지만 연말정산 잘 알지 않으면 돌려받기는 사용...,2024년 11월 19일,"안녕하세요. Won Choi 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
1,최유연,5,"증권부분이 너무 빈약해요. 이평선, 분봉, 틱봉 자유롭게 수치를 설정할 수 있었음 ...",2025년 1월 18일,"안녕하세요. 최유연 님, 토스팀입니다. 토스증권 사용하시면서 주신 소중한 의견 너무..."
2,EXPRESS,5,주식 UI에서 홈과 관심 종목을 나눈 것도 불편한데 이번 자주 사용하는 계좌 업데이...,2025년 2월 25일,"안녕하세요. EXPRESS 님, 토스팀입니다. 우선 토스증권 이용에 불편을 드려 죄..."
3,JS P,5,언제 한 번 대대적으로 앱 퍼포먼스 최적화를 했으면 좋겠습니다. 예전엔 이러지 않았...,2025년 2월 28일,"안녕하세요. JS P 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노력하였..."
4,AndPeter,5,앱 최적화 좀 해주세요! 무슨 메모리를 1GB나 잡아먹고 패킷전송이 하루에 80만건...,2025년 3월 1일,"안녕하세요. AndPeter 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 ..."
...,...,...,...,...,...
525,김민,5,"아니 업데이트 방금하니까, 주문수정하는게 가격 바꾸는게 안되네요? 무조건 취소하고 ...",2024년 11월 11일,"안녕하세요 김민님, 토스팀입니다. 우선 토스증권 서비스 이용에 불편을 드려 정말 죄..."
526,최고운,5,업데이트 후 동영상 재생광고를 선택권없이 무조건 시청해야 하군요. wi-fi 환경이...,2023년 6월 3일,"안녕하세요. 최고운님. 토스 고객센터입니다. 먼저, 이용에 불편을 드려 죄송합니다...."
527,블리,5,"라이브쇼핑보고,포인트받기 시스템 변경후,어찌 주구장창 1포인트만 나오는지.........",2024년 4월 11일,"안녕하세요. 블리님, 토스 고객센터입니다. 먼저 서비스 이용에 불편을 드렸다면 대단..."
528,조명현,5,구석구석 숨어있던 버그를 잡다가 업데이트 설치가 안 되는 버그가 생긴 듯 합니다,2025년 2월 25일,"안녕하세요. 조명현 님, 토스팀입니다. 사용에 불편을 드린것 같아 마음이 무겁습니다..."
529,이예진,5,홈화면에 계좌 순서 설정한게 반영 안되게 바뀌었는지 이해가 안감 너무 불편함,2025년 2월 27일,"안녕하세요. 이예진 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주..."