# KNN_SVM_프로모션_효율예측분석

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import koreanize_matplotlib

In [2]:
mem = pd.read_csv("./data/member.csv")
tran = pd.read_csv("./data/transaction.csv")

* 쇼핑몰 고객 데이터, 프로모션 쿠폰을 발행하고 사용 여부 데이터 수집
* mem : 고객id, 최근 방문일, 사는 지역, 추천여부, 주요접속체널, 쿠폰사용여부(target)
* tran : 고객id, 구매수량, 총 구매금액
* 전통적 마케팅 분석 방법 RFM 기법을 활용해 고객 데이터에서 파생변수 생성 후 분석
* R: Recency: 현재일 - 최근 구매일
* F: Frequency: 구매빈도
* M: Monetary: 구매 금액
* 종속변수: conversion => 고객이 프로모션에 반응 했는가? 1 =yes, 0 = no

In [3]:
mem.head(2)

       id  recency   zip_code  is_referral channel  conversion
0  906145       10  Surburban            0   Phone           0
1  184478        6      Rural            1     Web           0

In [5]:
tran.head(5)

       id  num_item  total_amount
0  906145         5         34000
1  906145         1         27000
2  906145         4         33000
3  184478         4         29000
4  394235         4         33000

# KNN, SVM